language: python

python:
    - "2.7"

install:
    - wget https://bitbucket.org/pypy/pypy/get/ac4800c0db8a.zip
    - unzip ac4800c0db8a.zip
    - mv pypy-pypy-ac4800c0db8a ./pypy
    - pip install -r requirements.txt

script:
    - make test_all PYPYPATH=./pypy
    - make compile PYPYPATH=./pypy
    - make test_all_compiled PYPYPATH=./pypy
    - make wlvlang-jit PYPYPATH=./pypy
    - make test_all_jit PYPYPATH=./pypy
