language: python

python:
    - "2.7"

install:
    - wget https://bitbucket.org/pypy/pypy/get/ac4800c0db8a.zip
    - tar -x ac4800c0db8a.zip
    - mv ac4800c0db8a ./pypy

script:
    make test_all PYPYPATH=./pypy
    make compile PYPYPATH=./pypy
    make test_all_compiled PYPYPATH=./pypy
    make wlvlang-jit PYPYPATH=./pypy
    make test_all_jit PYPYPATH=./pypy
